# NOTE: This file provides production-specific overrides for the services
# defined in the base docker-compose.yml file.
# Ensure that your production environment provides a PostgreSQL database
# and that the DATABASE_URL environment variable for the 'api' and 'worker'
# services is correctly configured to point to it.
# The Prisma migrations (`prisma migrate deploy`) must be run against
# this production database as part of the deployment process.

services:
  api:
    deploy:
      resources:
        limits:
          cpus: "14"
          memory: 48G
        reservations:
          cpus: "8"
          memory: 32G

  worker:
    command: python -m dramatiq --processes 20 --threads 16 run_agent_background
    deploy:
      resources:
        limits:
          cpus: "14"
          memory: 48G
        reservations:
          cpus: "8"
          memory: 32G

  redis:
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 12G
        reservations:
          cpus: "1"
          memory: 8G

  rabbitmq:
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 12G
        reservations:
          cpus: "1"
          memory: 8G
